/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_dynamic_register_TestNdk */

#ifndef _Included_com_example_jni_dynamic_register_TestNdk
#define _Included_com_example_jni_dynamic_register_TestNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_dynamic_register_TestNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_1dynamic_1register_TestNdk_getString
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_example_jni_1dynamic_1register_TestNdk_diff
  (JNIEnv *, jclass, jstring, jstring, jint);
#ifdef __cplusplus
}
#endif
#endif
